files/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

app_name = 'files'

urlpatterns = [
    path('managerRegister/', views.managerRegister, name='manReg'),
    path('managerLogin/', views.managerLogin, name='manLog'),
    path('employeeLogin/', views.employeeLogin, name='empLog'),
    path('newPassword/', views.newPassword, name='newPass'),
    path('addEmployee/', views.addEmployee, name='addEmp'),
    path('logs/', views.logs, name='logs'),
    path('display/', views.display, name='display'),
    path('medicineName/', views.medicineName, name='logout'),
    path('employee/<int:employee_id>/', views.addComponent, name='addComponent'),

    # path('<int:med_id>/',views.add_component,name='constituent'),
    # path('list/',views.home,name='home'),
    # path('list/<int:id>/',views.retrieve_components,name='retrieve'),
]

server/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('files.urls')),
]

files/models.py
from django.db import models
from django.contrib.auth.models import User

class Employee(models.Model):
    email = models.EmailField(max_length=100, unique=True, default=None)
    name = models.CharField(max_length=100, default=None)
    manager_name = models.CharField(max_length=100,default=None)
    medicine_name = models.CharField(max_length=100,default=None)

    def __str__(self):
        return self.name

class Medicine(models.Model):
    manager = models.ForeignKey(User, on_delete=models.CASCADE, default=None)
    medicine_name = models.CharField(max_length=100, default=None)

    def __str__(self):
        return self.medicine_name

class Component(models.Model):
    key = models.ForeignKey(Medicine, on_delete=models.CASCADE, default=None)
    component_name = models.CharField(max_length=500,default=None)
    component_quantity= models.CharField(max_length=500, default=None)
    component_cost = models.CharField(max_length=500, default=None)  
    # def __str__(self):
    #     return self.component_name

class Log(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    name = models.CharField(max_length=100, default=None)
    component_name = models.CharField(max_length=500,default=None)
    component_quantity= models.CharField(max_length=500, default=None)
    component_cost = models.CharField(max_length=500, default=None)    

# class Key(models.Model):
#     medicine_name = models.CharField(max_length=100,default=None)
#     privateKey_1 = models.CharField(max_length=500,default=None)
#     privateKey_2 = models.CharField(max_length=500,default=None)
#     publicKey = models.CharField(max_length=500,default=None)

#     def __str__(self):
#         return self.medicine_name

files/forms.py
from django import forms
from .models import Employee
from django.contrib.auth.models import User

# class Medicine(forms.ModelForm):
#     class Meta:
#         model = Key
#         fields = ('medicine_name',)


# class Constituent(forms.ModelForm):
#     class Meta:
#         model = Component
#         fields = ('component_name','component_cost','component_quantity',)	

class ManagerForm(forms.ModelForm):
	password = forms.CharField(widget=forms.PasswordInput)
	class Meta:
		model = User
		fields = ('username', 'password',)
		help_texts = {'username': None, 'password': None}

files/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from .forms import ManagerForm
from . import paillier, AESCipher
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth import authenticate
from .models import Employee, Medicine, Component, Log
from django.conf import settings
from django.core.mail import send_mail
import random, datetime
from django.contrib.auth.decorators import login_required


def employeeLogin(request):
    if request.method == 'POST':
        email = request.POST['email'] 
        password = request.POST['password']       
        if Employee.objects.filter(email=email).exists() and password=="password":
            element = Employee.objects.get(email=email)
            return redirect('/employee/' + str(element.id))
            # return redirect('addComponent', employee_id=element.id)

    return render(request, 'files/employeeLogin.html')

def newPassword(request):
    return render(request, 'files/newPassword.html')

def managerLogin(request):
    logout(request)
    if request.POST:
        username = request.POST.get('email')
        password = request.POST.get('password')
        print(username,password)
        user = authenticate(username = username, password = password)

        if user is not None:
            if user.is_active:
                login(request,user)
                return redirect('/addEmployee/')

    return render(request, 'files/managerLogin.html')

def managerRegister(request):
    if request.method == 'POST':

        user_form = ManagerForm(request.POST)
        medicine = request.POST.get('medicine')
        if user_form.is_valid():
            user = user_form.save(commit=False)
            username = user_form.cleaned_data['username']
            password = user_form.cleaned_data['password']
            user.set_password(password)
            user.save()
            priv,pub = paillier.generate_keypair(256)
            aes_key = AESCipher.gen_key()
            a = priv.get_list()
            priv1 = a[0]
            priv2 = a[1]
            file_key = password
            medicine = AESCipher.encrypt(medicine,aes_key)
            medicine = medicine.hex()
            med = Medicine.objects.create(manager = user, medicine_name = medicine)
            med.save()
            while len(file_key) != 32:
                file_key = file_key + str(random.randint(0,9))
            file_key = file_key.encode('UTF-8')
            print()
            print("pub " + str(type(pub)) + " " + str(pub))
            print("priv1 " + str(type(priv1)))
            print("priv2 " + str(type(priv2)))
            print("aes_key " + str(type(aes_key)) + " " + str(aes_key))
            print()
            f = open("manager.txt","w+")
            f.write(str(pub) + "\n")
            f.write(str(priv1) + "\n")
            f.write(str(priv2) + "\n")
            f.write(aes_key.hex())
            f.close()
            #AESCipher.encrypt_file(password,'manager.txt')
            f = open("employee.txt","w+")
            f.write(str(pub) + "\n")
            f.write(aes_key.hex())
            f.close()
            #AESCipher.encrypt_file('password','employee.txt')
            login(request, authenticate(username=username, password=password))

            return redirect('/addEmployee/')
    else:
                user_form = ManagerForm()

    return render(request,'files/managerRegister.html', {'user_form': user_form})               



login_required(login_url='files:manLog')
def addEmployee(request):
    user = User.objects.get(username = request.user.username)
    med = Medicine.objects.get(manager = user)
    if request.method == 'POST':
        emp_name = request.POST['inputName']
        emp_email = request.POST['inputEmail3']
        print(emp_name)
        emp_obj = Employee.objects.create(email=emp_email,name=emp_name,manager_name = user.username,medicine_name = med.medicine_name )
        emp_obj.save()
        subject = "Important Notfication"
        message = 'Following is your username and password to login in DevMust Impex ' \
                  'Username: ' + emp_email + ' Password: password'
        from_email = settings.EMAIL_HOST_USER
        to_list = [emp_email,from_email]
        send_mail(subject=subject,from_email=from_email,message=message,recipient_list=to_list,fail_silently=True)
        return render(request, 'files/addEmployee.html')
    else:
        return render(request,'files/addEmployee.html')


login_required(login_url='files:manLog')
def logs(request):
    log = Log.objects.all()
    file = open('manager.txt')
    all_lines = file.readlines() 
    pub = int(all_lines[0])
    priv1 = int(all_lines[1])
    priv2 = int(all_lines[2])
    aes = all_lines[3]
    aes = bytes.fromhex(aes) 
    values = []

    ctr = 1
    for item in log: 
        comp_name = item.component_name
        comp_name = bytes.fromhex(comp_name)
        name = AESCipher.decrypt(aes, comp_name)
        quantity = paillier.decrypt(priv1, priv2, pub, int(item.component_quantity)) 
        cost = paillier.decrypt(priv1, priv2, pub, int(item.component_cost)) 
        value = {}
        value['ctr'] = ctr
        value['created'] = item.created
        value['ename'] = item.name
        value['cname'] = name
        value['quantity'] = quantity
        value['cost'] = cost
        values.append(value)
        ctr = ctr+1

    return render(request, 'files/logs.html', {'values': values})

login_required(login_url='files:manLog')
def display(request):
    file = open('manager.txt')
    all_lines = file.readlines() 
    pub = int(all_lines[0])
    priv1 = int(all_lines[1])
    priv2 = int(all_lines[2])
    aes = all_lines[3]
    aes = bytes.fromhex(aes) 
    #comp = Component.objects.all()
    user = User.objects.get(username = request.user)
    med = Medicine.objects.get(manager = user)
    comp = Component.objects.filter(key = med)

    med_name = med.medicine_name
    med_name = bytes.fromhex(med_name)
    med_name = AESCipher.decrypt(aes, med_name)
    values = []

    ctr = 1
    for item in comp: 
        comp_name = item.component_name
        comp_name = bytes.fromhex(comp_name)
        name = AESCipher.decrypt(aes, comp_name)
        quantity = paillier.decrypt(priv1, priv2, pub, int(item.component_quantity)) 
        cost = paillier.decrypt(priv1, priv2, pub, int(item.component_cost)) 
        value = {}
        value['ctr'] = ctr
        value['name'] = name
        value['quantity'] = quantity
        value['cost'] = cost
        values.append(value)
        ctr = ctr+1

    return render(request, 'files/display.html', {'values':values, 'med_name': med_name})

def medicineName(request):
    return render(request, 'files/medicineName.html')    

login_required(login_url='files:empLog')
def addComponent(request, employee_id):

    element = Employee.objects.get(id=employee_id)
    medicine = Medicine.objects.get(medicine_name = element.medicine_name)
    file = open('employee.txt')
    all_lines = file.readlines()
    pub_key = int(all_lines[0])
    aes_key = all_lines[1]
    aes_key = bytes.fromhex(aes_key)

    med_name = medicine.medicine_name
    med_name = bytes.fromhex(med_name)
    med_name = AESCipher.decrypt(aes_key, med_name)

    if request.method == 'POST':
        employee_name = element.name
        date_field = datetime.datetime.now()
        name = request.POST['inputName']
        quantity = request.POST['inputQuantity']
        cost = request.POST['inputCost'] 

        new_name = AESCipher.encrypt(name, aes_key)
        new_name = new_name.hex()
        new_quantity = paillier.encrypt(pub_key, int(quantity))
        new_cost= paillier.encrypt(pub_key, int(cost)) 

        log = Log.objects.create(created=date_field, name = employee_name, component_name=new_name, component_quantity=new_quantity, component_cost=new_cost)
        log.save() 

        if Component.objects.filter(component_name=new_name).exists():
            obj = Component.objects.get(component_name=new_name)
            obj.component_quantity = paillier.e_add(pub_key, int(obj.component_quantity), int(new_quantity))
            obj.component_cost = paillier.e_add(pub_key, int(obj.component_cost), int(new_cost))
            obj.save()            
        else:
            form = Component.objects.create(key = medicine ,component_name=new_name, component_quantity=new_quantity, component_cost=new_cost)
            form.save() 
        # return render(request, 'files/employee.html')              

    return render(request, 'files/employee.html', {'employee':element, 'med_name': med_name})

# def register(request):
#     medicine_name = "Crocin"
#     file = open('manager.txt')
#     all_lines = file.readlines()
#     key = all_lines[3]
#     key = key[2:-1]
#     key = key.encode('UTF-8')
#     encrypt_msg = AESCipher.encrypt(medicine_name, key)

#     return HttpResponse("<h1>Holla modamustfakaa</h1>")

# def register_med(request):

#     if request.method =='POST':
#         medicine = Medicine(request.POST)
#         if medicine.is_valid():
#             medicine1 = medicine.save(commit=False)
#             priv,pub = paillier.generate_keypair(256)
#             a = priv.get_list()
#             priv1=a[0]
#             priv2 = a[1]
#             medicine1.privateKey_1 = priv1
#             medicine1.privateKey_2 = priv2
#             medicine1.publicKey = pub
#             medicine1.save()

#             return redirect('/home/')
#     else:
#         medicine = Medicine()
#     return render(request,'files/test.html',{'medicine':medicine})

# def add_component(request,med_id):
#     medic = Key.objects.get(id = med_id)
#     if request.method == 'POST':
#         constituent = Constituent(request.POST)
#         if constituent.is_valid():
#             constituent1 = constituent.save(commit=False)
#             quant = int(constituent1.component_quantity)

files/templates/files/addEmployee.html
{% extends "files/base_manager.html" %}

{% block content %}

<div class="card card-outline-secondary">
    <div class="card-header text-center">
        <h3 class="mb-0">Add Employee</h3>
    </div>
    <div class="card-body">
        <form method='post'>
            {% csrf_token %}
            <br>
            <div class="form-group">
                <label for="inputName">Enter Employee Name</label>
                <input name="inputName" type="text" class="form-control" id="inputName" placeholder="Name" required="">
            </div>
            
            <br>
            <div class="form-group">
                <label for="inputEmail3">Enter Employee E-mail Address</label>
                <input name="inputEmail3" type="email" class="form-control" id="inputEmail3" placeholder="E-Mail" required="">
            </div>

            
            <br>
            <div class="form-group text-center">
                <button type="submit" class="button btn btn-outline-success">Submit</button>
            </div>
        </form>
	</div>
</div>

{% endblock content %}

files/templates/files/base_login.html
<!DOCTYPE html>
<html>
<head>
	<title>Login Page</title>
	
	{% load static %}
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
	<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.4.3/css/mdb.min.css">

	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	<link rel="stylesheet" type="text/css" href="{% static 'files/login.css' %}">

	<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>	

	<!-- Jquery -->
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>	

</head>
<body>

	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">
					<div class="brand_logo_container">
						<img src="{% static 'files/images/logo1.jpg' %}" class="brand_logo" alt="Logo">
					</div>
				</div>
				<div class="d-flex justify-content-center form_container">
					<!-- <form>
						<h2 class="text-light text-center"><b>Login Form</b></h2>
						<br>
						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fa fa-user"></i></span>
							</div>
							<input type="text" name="" class="input form-control mx-2" id="username" placeholder="username">
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fa fa-key"></i></span>
							</div>
							<input type="password" name="" class="input form-control mx-2" id="password" placeholder="password">
						</div>
						<br>
						<div class="d-flex justify-content-center mt-3 login_container">
				 			<button type="button" name="button" class="btn login_btn">Login</button>
				   		</div>
				   		<br>
					</form> -->
					{% block content %}
					{% endblock content %}

				</div>
			</div>
		</div>
	</div>

</body>
</html>					

files/templates/files/base_manager.html
<!DOCTYPE html>
<html>
<head>
	<title>Manager Page</title>
	

	{% load static %}
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
	<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.4.3/css/mdb.min.css">

	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	<link rel="stylesheet" type="text/css" href="{% static 'files/manager.css' %}">

	<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>	

	<!-- Jquery -->
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>	

</head>
<body>
	<div class="main">
<!-- 		<div class="header">
			<img src="./logo1.jpg" class="logo img-responsive">
			<h2>DevMust Impex</h2>
		</div> -->
		<nav class="header navbar navbar-expand navbar-dark bg-dark">
		  	<a class="navbar-brand d-flex" href="#">
		    	<img src="{% static 'files/images/logo1.jpg' %}" class="logo d-inline-block align-top" alt=""> 
		    	<h4 class="my-auto"><b>DevMust Impex</b></h4>
		  	</a>
			<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
			    <span class="navbar-toggler-icon"></span>
			</button>		  	
			<div class="collapse navbar-collapse justify-content-end" id="navbarCollapse">
			  	<ul class="navbar-nav">
			    	<li class="nav-item mx-1">
			      		<a class="nav-link" href="{% url 'files:addEmp' %}">Add Employee</a>
			    	</li>
			    	<li class="nav-item mx-1">
			      		<a class="nav-link" href="{% url 'files:display' %}">Display Information</a>
			    	</li>	
			    	<li class="nav-item mx-1">
			      		<a class="nav-link" href="{% url 'files:logs' %}">Logs</a>
			    	</li>			    	
			    	<li class="nav-item mx-1">
			      		<a class="nav-link" href="{% url 'files:manLog' %}">Logout</a>
			    	</li>			    			    				    	
			  	</ul>
			</div>		  	
		</nav>

		<br><br><br>
		<div class="container content">

			{% block content %}
			{% endblock content %}

		</div>
		<br><br>
	</div>

</body>
</html>			

files/templates/files/display.html
{% extends "files/base_manager.html" %}

{% block content %}

<div class="card-header text-center">
    <h3 class="mb-0">{{ med_name }} Details</h3>
</div>
<br>
<table class="display table table-hover text-center">
  	<thead>
        <tr>
          	<th><b>#</b></th>
          	<th><b>Component Name</b></th>
          	<th><b>Quantity</b></th>
          	<th><b>Total Cost</b></th>
        </tr>
  	</thead>
  	<tbody>
      {% for value in values %}
        <tr>
          <td scope="row">{{ value.ctr }}</td>
          <td>{{ value.name }}</td>
          <td>{{ value.quantity }}</td>
          <td>{{ value.cost }}</td>
        </tr>
      {% endfor %}
  	</tbody>
</table>

{% endblock content %}

files/templates/files/employee.html
<!DOCTYPE html>
<html>
<head>
	<title>Employee Page</title>
	

	{% load static %}
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
	<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.4.3/css/mdb.min.css">

	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	<link rel="stylesheet" type="text/css" href="{% static 'files/employee.css' %}">

	<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>	

	<!-- Jquery -->
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>	

</head>
<body>
	<div class="main">
<!-- 		<div class="header">
			<img src="./logo1.jpg" class="logo img-responsive">
			<h2>DevMust Impex</h2>
		</div> -->
		<nav class="header navbar navbar-light bg-dark">
		  	<a class="navbar-brand d-flex" href="#">
		    	<img src="{% static 'files/images/logo1.jpg' %}" class="logo d-inline-block align-top" alt=""> 
		    	<h3 class="my-auto text-light"><b>DevMust Impex</b></h3>
		  	</a>
		  	<ul class="navbar-nav ml-auto text-light">
			    <li class="nav-item">
			      	<h5>User: {{ employee.name }}</h5>
			    </li>	
			    <li class="nav-item">
			      	<h5>Manager: {{ employee.manager_name }}</h5>
			    </li>
                <li class="nav-item">
			      	<h5><a href="{% url 'files:empLog' %}">Logout</a></h5>
			    </li>
			</ul>

		</nav>

		<br><br><br>
		<div class="container content">
			<div class="card card-outline-secondary">
                        <div class="card-header text-center">
                            <h3 class="mb-0">Add {{ med_name }} Component Details</h3>
                        </div>
                        <div class="card-body">
                            <form class="form" method="POST" role="form" autocomplete="off">
                            	{% csrf_token %}
                            	<br>
                                <div class="form-group">
                                    <label for="inputName">Component Name</label>
                                    <input type="text" class="form-control" id="inputName" name="inputName" placeholder="Name" required="">
                                </div>
                                <br>
                                <div class="form-group">
                                    <label for="inputQuantity">Component Quantity</label>
                                    <input type="number" class="form-control" id="inputQuantity" name="inputQuantity" placeholder="Quantity" required="">
                                </div>
                                <br>
                                <div class="form-group">
                                    <label for="inputCost">Component Cost</label>
                                    <input type="number" class="form-control" id="inputCost" name="inputCost" placeholder="Cost" required="">
                                </div>
                                <br>
                                <div class="form-group text-center">
                                    <button type="submit" class="button btn btn-outline-success">Submit</button>
                                </div>
                            </form>
                        </div>
                    </div>
		</div>
		<br><br>
	</div>

</body>
</html>

files/templates/files/employeeLogin.html
{% extends "files/base_login.html" %}

{% block content %}

<form method="post">
	{% csrf_token %}
	<h3 class="text-light text-center"><b>Employee Login</b></h3>
	<br>
	<div class="input-group mb-3">
		<div class="input-group-append">
			<span class="input-group-text"><i class="fa fa-user"></i></span>
		</div>
		<input type="text" name="email" id="email" class="input form-control mx-2" value="" placeholder="User ID">
	</div>
	<div class="input-group mb-2">
		<div class="input-group-append">
			<span class="input-group-text"><i class="fa fa-key"></i></span>
		</div>
		<input type="password" name="password" id="password" class="input form-control mx-2" value="" placeholder="Password">
	</div>
	<br>
	<div class="d-flex justify-content-center mt-3 login_container">
		<button type="submit" name="button" class="btn login_btn">Login</button>
	</div>
	<br>
</form>		

{% endblock content %}	
			

files/templates/files/logs.html
{% extends "files/base_manager.html" %}

{% block content %}

<div class="card-header text-center">
    <h3 class="mb-0">{{medicine_name}}</h3>
</div>
<br>
<table class="display table table-hover text-center">
  	<thead>
        <tr>
            <th><b>#</b></th>
            <th><b>Timestamp</b></th>
            <th><b>Employee Name</b></th>
          	<th><b>Component Name</b></th>
          	<th><b>Component Quantity</b></th>
          	<th><b>Component Cost</b></th>
        </tr>
  	</thead>
  	<tbody>
      {% for value in values %}
        <tr>
          <td scope="row">{{ value.ctr }}</td>
          <td>{{ value.created }}</td>
          <td>{{ value.ename }}</td>
          <td>{{ value.cname }}</td>
          <td>{{ value.quantity }}</td>
          <td>{{ value.cost }}</td>
        </tr>
      {% endfor %}
  	</tbody>
</table>

{% endblock content %}

files/templates/files/managerLogin.html
{% extends "files/base_login.html" %}

{% block content %}

<form method="post">
	{% csrf_token %}
	<h3 class="text-light text-center"><b>Manager Login</b></h3>
	<br>
	<div class="input-group mb-3">
		<div class="input-group-append">
			<span class="input-group-text"><i class="fa fa-user"></i></span>
		</div>
		<input type="text" name="email" id="email" class="input form-control mx-2" value="" placeholder="User ID">
	</div>
	<div class="input-group mb-2">
		<div class="input-group-append">
			<span class="input-group-text"><i class="fa fa-key"></i></span>
		</div>
		<input type="password" name="password" id="password" class="input form-control mx-2" value="" placeholder="Password">
	</div>
	<br>
	<div class="d-flex justify-content-center mt-3 login_container">
		<button type="submit" name="button" class="btn login_btn">Login</button>
	</div>
	<br>
    <a href="{% url 'files:manReg' %}">Register as Manager</a>
    <br>
</form>

{% endblock content %}

files/templates/files/newPassword.html
{% extends "files/base_login.html" %}

{% block content %}

<form method="post">
	{% csrf_token %}
	<h3 class="text-light text-center"><b>Enter new password</b></h3>
	<br>
	<div class="input-group mb-2">
		<div class="input-group-append">
			<span class="input-group-text"><i class="fa fa-key"></i></span>
		</div>
		<input type="password" name="" class="input form-control mx-2" value="" placeholder="Password">
	</div>
	<br>
	<div class="d-flex justify-content-center mt-3 login_container">
			<button type="button" name="button" class="btn login_btn">Continue</button>
		</div>
		<br>
</form>		

{% endblock content %}	